using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Microsoft.IdentityModel.JsonWebTokens;
using Microsoft.IdentityModel.Tokens;
using Server.Models;
using Server.Services;

namespace Server.Helpers;
public static class JwtTokenHelper {
    public static string GenerateToken(User user, IConfiguration configuration) {
        var jwtSection = configuration.GetSection("Jwt");
        var key = jwtSection.GetValue<string>("Key");
        var issuer = jwtSection.GetValue<string>("Issuer");
        var audience = jwtSection.GetValue<string>("Audience");
        var expiryMin = jwtSection.GetValue<int>("ExpiryMinutes");

        var securityKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(key ?? throw new Exception("jwt key is not set")));
        var credentials = new SigningCredentials(securityKey, SecurityAlgorithms.HmacSha256);

        Claim[] claims = [
            new Claim("nam", user.Username!),
            new Claim("uid", user.Id.ToString()),
            new Claim("pwd", user.PasswordHash.ToString())
        ];

        var tokenDescriptor = new SecurityTokenDescriptor {
            Issuer = issuer,
            Audience = audience,
            Subject = new ClaimsIdentity(claims),
            Expires = DateTime.UtcNow.AddMinutes(expiryMin),
            SigningCredentials = credentials
        };

        // don't use JwtSecurityTokenHandler because the server can't read tokens generated by it for some reason
        return new JsonWebTokenHandler().CreateToken(tokenDescriptor);
    }

    public static async Task<long> GetId(IUserService users, ClaimsPrincipal user) {
        long val = long.Parse(user.FindFirst("uid")?.Value ?? throw new UnauthorizedAccessException("Invalid authorization"));
        User? u = await users.GetByIdAsync(val);
        if (u == null || u.IsDeleted || u.Username != user.FindFirst("nam")?.Value || u.PasswordHash != user.FindFirst("pwd")?.Value)
            throw new UnauthorizedAccessException("User does not exist");
        Console.WriteLine($"Extracted user id from token: {val}");
        return val;
    }
}